OpenDatabase("Results/r01wingNwake*.plt database")
AddPlot("Mesh", "mesh", 1, 1)
OpenDatabase("Results/r02wingNwake*.plt database")
AddPlot("Mesh", "mesh", 1, 1)
OpenDatabase("Results/r03wingNwake*.plt database")
AddPlot("Mesh", "mesh", 1, 1)
OpenDatabase("Results/r04wingNwake*.plt database")
AddPlot("Mesh", "mesh", 1, 1)
OpenDatabase("Results/r05wingNwake*.plt database")
AddPlot("Mesh", "mesh", 1, 1)
DrawPlots()
