main – VOLCANOR
main Program
964 statements
Source File
Uses
libMath
libPostprocess
libCommon
Calls
Contents
None
Call graph
main calls filaments2file, geomsurface2file, force2file, probes2file, params2file, skew2file, geom2file, vel_order2_fwake, print_status, init_plots, gamma2file, vind_onfwake_byrotor, matmulax, vind_onnwake_byrotor, vel_order2_nwake, inflow2file, tip2file, isinverse, readconfig, cross_product, dynamics2file
force2file calls 9, 11, 16
probes2file calls 6
skew2file calls 2
matmulax calls dgemv
isinverse calls matmul2
matmul2 calls dgemm