cross_product – VOLCANOR
cross_product Function
7 statements
Source File
public function cross_product(aVec, bVec)
Compute cross product between two 3d vectors
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(3) :: aVec
real(kind=dp), intent(in), dimension(3) :: bVec
Return Value real(kind=dp),dimension(3)
Called by
Contents
None
Call graph
wingpanel_calcn calls cross_product
main calls cross_product
blade_dirliftdrag calls cross_product
blade_calc_force_alphagamma calls cross_product
blade_calc_force calls cross_product
wingpanel_calc_area calls cross_product
blade_seccoeffstosecforces calls cross_product
rotor_init calls cross_product