linspace – VOLCANOR
linspace Function
11 statements
Source File
public function linspace(xstart, xend, nx) result(xout)
Return linearly-spaced array over a specified interval
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: xstart
Start value of sequence
real(kind=dp), intent(in) :: xend
End value of sequence
integer, intent(in) :: nx
Number of points sequence
Return Value real(kind=dp),dimension(nx)
Array of real numbers
Called by
Contents
None
Call graph
rotor_init calls linspace, tanspace, cosspace, halfsinspace
pfwake_update calls linspace
tanspace calls linspace
cosspace calls linspace
halfsinspace calls linspace