lsq2_scalar – VOLCANOR
lsq2_scalar Function
22 statements
Source File
public function lsq2_scalar(xQuery, xData, yData)
Linear Least Squares fitting (2nd order)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: xQuery
real(kind=dp), intent(in), dimension(:) :: xData
real(kind=dp), intent(in), dimension(:) :: yData
Return Value real(kind=dp)
Calls
Called by
Contents
None
Call graph
lsq2_scalar calls inv
inv calls print_mat
lsq2 calls lsq2_scalar
blade_calc_secchordwiseresvel calls lsq2