rotor_init – VOLCANOR
rotor_init Subroutine
756 statements
Source File
public subroutine rotor_init(this, rotorNumber, density, dt, nt, switches, sourceRotor)
Uses
libMath
Initialize variables of rotor geometry and wake
Arguments
Type Intent Optional Attributes Name
class(rotor_class) :: this
integer, intent(in) :: rotorNumber
real(kind=dp), intent(in) :: density
real(kind=dp), intent(inout) :: dt
integer, intent(inout) :: nt
type(switches_class), intent(inout) :: switches
type(rotor_class), optional :: sourceRotor
Calls
Contents
None
Call graph
rotor_init calls dsign, length3d, tanspace, cosspace, halfsinspace, linspace, cross_product, unitvec
tanspace calls linspace
cosspace calls linspace
halfsinspace calls linspace